name: Cascade Merge

on:
  #schedule:
  #  - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  merge_cascade:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Set a timeout for the workflow run

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'automated-github-actions-via-hans'
        git config --global user.email 'hans.boeren@qframe.be'

    - name: Check for changes between develop and develop-refactor-current
      id: check_changes_refactor
      run: |
        git fetch origin
        if git diff --quiet origin/develop origin/develop-refactor-current; then
          echo "No changes detected"
          echo "changes=false" >> $GITHUB_ENV
        else
          echo "Changes detected"
          echo "changes=true" >> $GITHUB_ENV
        fi

    - name: Merge develop into develop-refactor-current
      if: env.changes == 'true'
      run: |
        git fetch origin
        git checkout -b develop-refactor-current-merge origin/develop-refactor-current
        git merge origin/develop || {
          echo "Conflict detected, aborting merge"
          git merge --abort
          exit 1
        }
        git push origin develop-refactor-current-merge

    - name: Create PR for develop-refactor-current
      if: env.changes == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create --base develop-refactor-current --head develop-refactor-current-merge --title 'Merge develop into develop-refactor-current' --body 'Automated merge of develop into develop-refactor-current'

    - name: Add 'automated' label to PR
      if: env.changes == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pr_url=$(gh pr view --json url --jq '.url' develop-refactor-current-merge)
        pr_number=$(gh pr view $pr_url --json number --jq '.number')
        gh pr edit $pr_number --add-label "automated"

    # This works kind off, not optimal or cost effective
    - name: Wait for PR checks to complete
      if: env.changes == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pr_url=$(gh pr view --json url --jq '.url' develop-refactor-current-merge)
        while true; do
          merge_state_status=$(gh pr view $pr_url --json mergeStateStatus --jq '.mergeStateStatus')
          if [[ $merge_state_status == 'BLOCKED' ]]; then
            echo "Merge state is BLOCKED. Exiting..."
            exit 1
          elif [[ $merge_state_status == 'CLEAN' || $merge_state_status == 'UNSTABLE' ]]; then
            echo "Merge state is $merge_state_status. Breaking loop..."
            break
          else
            echo "Current merge state: $merge_state_status. Waiting for PR checks to complete..."
            sleep 60
          fi
        done

    - name: Complete PR after checks
      if: env.changes == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pr_url=$(gh pr view --json url --jq '.url' develop-refactor-current-merge)
        gh pr merge $pr_url --auto --merge --delete-branch

    #
    #  ToDo do this for other branches
    #  Depends on the the strategy you whish to apply
    #  - either use a sleep loop and so on (not cost effective)
    #  - combine multiple workflow's based on time or Webhook for pr status?
    # ...
  
    - name: Notify team of conflicts
      if: failure()
      run: |
        echo "Conflict detected during merging process. Please resolve the conflicts manually."
        # You can add Slack or email notifications here